# Generated by Django 5.0.2 on 2024-06-26 06:51

import django.db.models.deletion
import tag_me.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Author')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField(verbose_name='Article')),
                ('tag', tag_me.db.models.fields.TagMeCharField(blank=True, help_text='A tag for the Article', max_length=255, null=True, verbose_name='Article Tag')),
                ('user_tag', tag_me.db.models.fields.TagMeCharField(blank=True, help_text='A tag for the Article', max_length=255, null=True, verbose_name='Article User Tag')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.author', verbose_name='Article Author')),
            ],
            options={
                'verbose_name': 'Blog Article',
                'verbose_name_plural': 'Blog Articles',
            },
        ),
    ]
