# Generated by Django 5.0.2 on 2024-07-02 03:35

import tag_me.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tag",
            field=tag_me.db.models.fields.TagMeCharField(
                blank=True,
                help_text="A tag for the Article",
                max_length=255,
                null=True,
                verbose_name="Article Choices Tag",
            ),
        ),
    ]
