# Generated by Django 4.2.4 on 2023-09-07 03:23

from django.db import migrations, models
import tag_me.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedFieldTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_field_1', tag_me.db.models.fields.TagMeCharField(max_length=255)),
                ('tagged_field_2', tag_me.db.models.fields.TagMeCharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tagged Field Test Model',
                'verbose_name_plural': 'Tagged Field Test Models',
            },
        ),
    ]
