# Generated by Django 5.0.2 on 2024-06-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagtestbase",
            name="name",
            field=models.CharField(
                help_text="This is the tag", max_length=50, verbose_name="Name"
            ),
        ),
    ]
