# Generated by Django 5.0.7 on 2024-08-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagtestbase",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="This is the tag",
                max_length=255,
                null=True,
                verbose_name="tags",
            ),
        ),
    ]
