# Generated by Django 5.0.2 on 2024-06-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertag',
            name='name',
            field=models.CharField(help_text='This is the tag', max_length=50, verbose_name='Name'),
        ),
    ]
