# Generated by Django 5.0.6 on 2024-07-11 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tag_me", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usertag",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_tags",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddConstraint(
            model_name="taggedfieldmodel",
            constraint=models.UniqueConstraint(
                fields=(
                    "content",
                    "model_name",
                    "model_verbose_name",
                    "field_name",
                    "field_verbose_name",
                ),
                name="unique_tagged_field_model",
            ),
        ),
        migrations.AddIndex(
            model_name="usertag",
            index=models.Index(
                fields=["user"], name="tag_me_user_user_id_cc2ba7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usertag",
            constraint=models.UniqueConstraint(
                fields=("user", "field_name", "name"),
                name="unique_user_field_tag",
            ),
        ),
    ]
