# Generated by Django 5.2.1 on 2025-10-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag_me", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemtag",
            name="search_tags",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A list of every tag created, for use in search tools",
                verbose_name="Search Tags",
            ),
        ),
        migrations.AddField(
            model_name="usertag",
            name="search_tags",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A list of every tag created, for use in search tools",
                verbose_name="Search Tags",
            ),
        ),
        migrations.AlterField(
            model_name="systemtag",
            name="tags",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The tags that are considered active and in use by the user",
                max_length=255,
                null=True,
                verbose_name="tags",
            ),
        ),
        migrations.AlterField(
            model_name="usertag",
            name="tags",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The tags that are considered active and in use by the user",
                max_length=255,
                null=True,
                verbose_name="tags",
            ),
        ),
    ]
