# Generated by Django 5.0.6 on 2024-07-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag_me", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="usertag",
            name="unique_user_field_tag",
        ),
        migrations.AddField(
            model_name="usertag",
            name="field_verbose_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Field verbose",
            ),
        ),
        migrations.AlterField(
            model_name="usertag",
            name="field_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Field name",
            ),
        ),
        migrations.AlterField(
            model_name="usertag",
            name="model_verbose_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Model verbose",
            ),
        ),
    ]
