# Generated by Django 5.0.6 on 2024-07-11 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag_me", "0003_remove_usertag_unique_user_field_tag_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="usertag",
            constraint=models.UniqueConstraint(
                fields=("user", "tagged_field"), name="unique_user_field_tag"
            ),
        ),
    ]
