# Generated by Django 6.0.1 on 2026-02-24 00:49
# Housekeeping moving to django 6

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tag_me", "0005_remove_taggedfieldmodel_unique_tagged_field_model_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="systemtag",
            name="tag_me_sys_tagged_field_idx",
        ),
        migrations.RemoveIndex(
            model_name="usertag",
            name="tag_me_user_tagged_user_idx",
        ),
    ]
